apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-c-prod
spec:
  selector:
    matchLabels:
      app: service-c  
  replicas: 1
  template:
    metadata:
      labels:
        app: service-c
        version: prod
    spec:
      containers:
      - name: service-c
        image: istiodemo/api:fail
        imagePullPolicy: Never
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
          - containerPort: 80
        env:
          - name: api_port
            value: "8080"
          - name: SERVICE_NAME
            value: "service-c-prod"
          - name: UPSTREAM_URI
            value: "http://worldclockapi.com/api/json/utc/now"
      imagePullSecrets:
      - name: regcred
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service-c
spec:
  hosts:
  - service-c
  http:
  - match:
    - uri:
        exact: /
    - uri:
        exact: /health
    route:
    - destination:
        host: service-c
        subset: prod
    retries:
      attempts: 4
      perTryTimeout: 2s              
---