# Configuration for metric instances
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: demorequestcount
  namespace: istio-system
spec:
  value: "1" # count each request 
  dimensions:
    source: source.service | "demoservice"
    destination: destination.service | "demodestination"
    message: '"Hello Istio!"'
  monitored_resource_type: '"Custom Demo Type"'
---
# Configuration for a Prometheus handler
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: demopromhandler
  namespace: istio-system
spec:
  metrics:
  - name: demo_request_count # Prometheus metric name
    instance_name: demorequestcount.metric.istio-system # Mixer instance name (fully-qualified)
    kind: COUNTER
    label_names:
    - source
    - destination
    - message
---
# Rule to send metric instances to a Prometheus handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: demoprom
  namespace: istio-system
spec:
  actions:
  - handler: demopromhandler.prometheus
    instances:
    - demorequestcount.metric

